# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 885cd91577902d79a1e73e1101531aa2aeef9486036096c8857687f07798e527a6e91c4ab31e525f114e9f028c88bcd68a19a23bae5f799fc2a5b8124b827784

test:
  secret_key_base: b37bf049f15552f54d88128f8d08c9f2a433a9767922119de13fa544e79cd4a427ea226e04858c2546435fa8b31fa21f6503c7ffeac758ae2c885ba67d857380

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
